services:
  catalogdb:
    image: postgres
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    restart: always

  catalog.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CatalogDB=Host=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
    ports:
      - "8080:80"
    depends_on:
      - catalogdb
    restart: on-failure

volumes:
  postgres_catalog: