services:
  catalogdb:
    image: postgres:latest
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    restart: always

  catalog.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS = 8080
      - ASPNETCORE_HTTPS_PORTS = 8081
      - ConnectionStrings__CatalogDB=Server=catalogdb;Database=CatalogDb;Port=5432;TrustServerCertificate=True;User Id=postgres;Password=postgres;
    ports:
      - "6000:8080"
      - "6060:8081"
    depends_on:
      - catalogdb
    restart: on-failure

volumes:
  postgres_catalog:  # This defines a named volume for PostgreSQL data persistence
