services:
  catalogdb:
    image: postgres:latest
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    restart: always
  basketdb:
    image: postgres:latest
    container_name: basket-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
    restart: always
  
  distributedcache:
    image: redis
    ports:
      - "6379:6379"
  
  orderdb:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sheeps100
    restart: always
    ports:
      - "1433:1433"
        

    
  catalog.api:
    build:
      context: .
      dockerfile: ./Services/Catalog.API/Dockerfile
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__CatalogDB=Server=catalogdb;Database=CatalogDb;Port=5432;TrustServerCertificate=True;User Id=postgres;Password=postgres;
    ports:
      - "6000:8080"
      - "6060:8081"
    depends_on:
      - catalogdb
    restart: on-failure
    
  basket.api:
    build:
      context: .
      dockerfile: ./Services/Basket.API/Dockerfile
    container_name: basket-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
      - ASPNETCORE_HTTPS_PORTS=8083
      - ConnectionStrings__BasketDB=Server=basketdb;Database=BasketDb;Port=5432;TrustServerCertificate=True;User Id=postgres;Password=postgres;
      - ConnectionStrings__Redis=distributedcache:6379
    ports:
      - "6001:8082"
      - "6061:8083"
    depends_on:
      - basketdb
      - distributedcache
    restart: on-failure
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: ./Services/Discount.Grpc/Discount.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Data Source=/app/discountdb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - discount_data:/app/

  ordering.api:
    build:
      context: .
      dockerfile: ./Services/Ordering/Ordering.API/Dockerfile
    container_name: ordering-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8084
      - ASPNETCORE_HTTPS_PORTS=8085
      - ConnectionStrings__Database=Server=localhost,1433;Database=master;User Id=SA;Password=sheeps100;TrustServerCertificate=True;
    ports:
      - "6003:8084"
      - "6063:8085"
    depends_on:
      - orderdb
    restart: on-failure
    volumes:
      - order_data:/app/
volumes:
  postgres_catalog:  # This defines a named volume for PostgreSQL data persistence
  postgres_basket:  # This defines a named volume for PostgreSQL data persistence
  discount_data:  # This defines a named volume for PostgreSQL data persistence
  order_data: