services:
  catalogdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    restart: always

  catalog.api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CatalogDB=Server=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
    ports:
      - "8080:80"
    depends_on:
      - catalogdb
    restart: on-failure
  
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
    